name: test_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_svg: any
  google_fonts: any

  async: any
  collection: any
  meta: any
  go_router: any

  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
